### ISSUE TITLE
Replace PARAMETERS with separate parameters for function

### ISSUE THREAD

**Issue by stefaneng** [helen-zhu/ConsensusPeaks#5]
In many of the functions, a single `PARAMETERS` is passed as an argument. To be more consistent and explicit about what is passed to the function parameters should be extracted out as arguments. For example

If we have `PARAMETERS.log_file = "/log"`
```{r}
g <- function(PARAMETERS) {
  // Do something with PARAMETERS.log_file
}
```

should become
```{r}
g <- function(log_file) {
  // Do something with log_file
}
```

We can then add Roxygen documentation for each argument so the package is easier to use and contribute to. Also for our own sanity when we need to make changes in the future.

**Comment by helen-zhu** [comment]
Sounds great :)
